### ISSUE TITLE
Ensure a valid URI

### ISSUE THREAD

**Issue by vhschlenker** [Mari-Wie/ArchCNL#120]
Commit 049d30af43e16f1e0223f43c8ebb2127269abc7c was the result of running and fixing the newly structured parser on the [CWA Testresultserver](https://github.com/corona-warn-app/cwa-testresult-server/).

We should ensure, that the URI is always valid [here](https://github.com/Mari-Wie/ArchCNL/blob/049d30af43e16f1e0223f43c8ebb2127269abc7c/owlify-famix/src/main/java/org/archcnl/owlify/famix/codemodel/Method.java#L143).

But I'm not sure, what a valid URI can contain, and what we should replace.

@nizap What do you think?

**Comment by nizap** [comment]
After some research, the [percent notation](https://en.wikipedia.org/wiki/Percent-encoding) seems suitable. I will add the corresponding code in `FamixOntology.FamixClasses.individualName()` so that it is used consistently in the different parsers. Also, removing spaces might be problem (e.g. `method(Some ClassParam)` and `method(SomeClass Param)` would have colliding URIs). I think that replacing spaces by a `-` (being an invalid character for method signatures every programming language I have encountered) might solve this (`method(Some-ClassParam)` vs `method(SomeClass-Param)`).

I will add these changes right now.
