### ISSUE TITLE
Violations can be added to the wrong rules

### ISSUE THREAD

**Issue by vhschlenker** [Mari-Wie/ArchCNL#176]
While using ArchCNL, I encountered a very weird problem.
I got violations, where the resulting triple of subject, predicate and object had nothing to with the CNL-Rule.
For example, neither the subject, predicate nor object matched the CNL-Rule.
After far too much debugging, head-scratching and rewriting rules and mappings, I found the reason.

The `OnlyCanRuletype` [adds](https://github.com/Mari-Wie/ArchCNL/blob/d0b60d559ec7b8c2b3ed4ef966428a14e24a3e01/org.architecture.cnl.parent/org.architecture.cnl/src/main/java/org/architecture/cnl/generator/ArchcnlGenerator.java#L265) a DomainRangeAxiom with its triples.
This is [implemented](https://github.com/Mari-Wie/ArchCNL/blob/d0b60d559ec7b8c2b3ed4ef966428a14e24a3e01/owl-creator/src/main/java/org/archcnl/owlcreator/impl/OWLAPIImpl.java#L168), so that an Object Property Domain is added for property, subject and property, object.

According to the [syntax](https://www.w3.org/TR/owl2-syntax/), this "Object Property Domain" restricts the property to the domain of the subject, and  also the object.

Let me give an example.
The rule "Only Testresultserver can store a TestResult." results in two axioms: "store" is restricted to "Testresultserver" and also "TestResult" is restricted to "store".
But this results in a violation of a rule which reads "Only Verificationserver can store a SomethingElse.", because "store" is limited to the domain of "Testresultserver" and "Verificationserver" is not a part of it.
So far, this is exactly to the specification of Dr. Sandra Schröders "OnlyCan"-Rule. That is just something one have to know when creating these rules.

But, there is a problem.
The violations of these axioms are not necessarily connected to the right rules.
At the place, where the [violations are created and numbered](https://github.com/Mari-Wie/ArchCNL/blob/895044d142e3abbfe52e051519d969bac3e59e46/stardog-wrapper/src/main/java/org/archcnl/stardogwrapper/impl/StardogICVAPIImpl.java#L113) there does not seem any connections to the rule index.
Futhermore, [while adding the violations to the rules](https://github.com/Mari-Wie/ArchCNL/blob/51efcba49db303f90f3af8af82872e3cbc9d5cf8/toolchain/src/main/java/org/archcnl/toolchain/CNLToolchain.java#L259), the only connecting that I can see is, that the index is hopefully the same.
Even though this seems to do the trick often enough, this fails with these axioms.

These axioms could create multiple violations. Even on rules which are not necessarily connected to them.
An Example again with the rules:
```
"Only Testresultserver can store an EntityA."
"Some differrent Rule"
"Only Verificationserver can store a EntityB."
"Only Verificationserver can store a EntityC.".
```
The "store" Relationship is between a repository and its entities.
This shows, how the structure is meant to be by these rules:
```
{Testresultserver:
    RepositoryA --store--> EntityA
}
{Verificationserver:
    RepositoryB --store--> EntityB
    RepositoryC --store--> EntityC
}
```
The triple `RepositoryA --store--> EntityA`is ok, since the domain of "store" is defined by the first rule to be "Testresultserver".

But all "store" Triples in "Verificationserver" are violated, since their domain is not "Testresultserver".
So we have two violations of the triple (Testresultserver, store, EntityA).
But through the index, these violations are connected to "Only Testresultserver can store an EntityA." and "Some different Rule".
As one can see, this could lead to great confusion why "Some different Rule" is violated.
And, furthermore, even if the connection would be to the right rules, the violation would be entirely in the rules itself and would not be connected to the actual code, that is analyzed.

**Comment by h-engelhardt** [comment]
I did some further digging and these are results I found:

Architecture violations are mapped to their original rule [here](https://github.com/Mari-Wie/ArchCNL/blob/master/toolchain/src/main/java/org/archcnl/toolchain/CNLToolchain.java#L272-L279). This maps the first violation of the retrieved list of violations to the first architecture rule of the list of architecture rules, but as these lists are not necessarily ordered this mapping is generally wrong as it can only be correct by pure luck. This is because the violations have no link to the architecture rule they violate and mapping them afterwards is infeasible.

Each rule is represented by an ArchitectureRule which contains the rule as an cnl-sentence and as an OWL constraint/ontology.
These rules are then added as constraints to the stardog database [here](https://github.com/Mari-Wie/ArchCNL/blob/master/toolchain/src/main/java/org/archcnl/toolchain/CNLToolchain.java#L249).
In [this method](https://github.com/Mari-Wie/ArchCNL/blob/master/stardog-wrapper/src/main/java/org/archcnl/stardogwrapper/impl/StardogICVAPIImpl.java#L49-L70) the rule as an OWL constraint/model (example how this looks at the bottom) is given to the stardog api which transforms it into an [constraint ](https://docs.stardog.com/archive/7.6.0/javadoc/snarl/com/complexible/stardog/icv/Constraint.html)(example of how this looks at the bottom). By doing it this way the link between the architecture rule as a cnl-sentence and the constraint saved in the stardog database is lost. Violations found in stardog are then only linked to the constraints in stardog and there is no knowledge which cnl-sentence they violate, but this is crucial for the user to know.

Therefore a link between the cnl-sentence and the constraint in stardog needs to be established.

Example of rule as OWL constraint:
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns="http://www.arch-ont.org/ontologies/architecture.owl#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#">
  <owl:Ontology rdf:about="http://www.arch-ont.org/ontologies/architecture.owl"/>
  <owl:Class rdf:about="http://www.arch-ont.org/ontologies/architecture.owl#EntityA"/>
  <owl:Class rdf:about="http://www.arch-ont.org/ontologies/architecture.owl#VerificationServer"/>
  <owl:ObjectProperty rdf:about="http://www.arch-ont.org/ontologies/architecture.owl#store">
    <rdfs:domain rdf:resource="http://www.arch-ont.org/ontologies/architecture.owl#VerificationServer"/>
    <rdfs:range>
      <owl:Class>
        <owl:unionOf rdf:parseType="Collection">
          <owl:Class rdf:about="http://www.arch-ont.org/ontologies/architecture.owl#EntityA"/>
        </owl:unionOf>
      </owl:Class>
    </rdfs:range>
  </owl:ObjectProperty>
</rdf:RDF>

Example of constraint in stardog (not the same as the example above):
Constraint{mQuery=SELECT DISTINCT *
WHERE {
   ?x0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.arch-ont.org/ontologies/architecture.owl#Aggregate> .
   FILTER NOT EXISTS {
      ?x0 <http://www.arch-ont.org/ontologies/architecture.owl#residein> ?x1 .
      ?x1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.arch-ont.org/ontologies/architecture.owl#DomainRing> .
   }
}
, mAxiom=SubClassOf(architecture:Aggregate,some(architecture:residein,architecture:DomainRing))}
